language: python
sudo: required
python:
  - "2.7"
services:
  - couchdb
env:
  global:
    - TZ=Europe/Kiev
cache: pip
addons:
  hosts:
   - couchdb
before_install:
  - export BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - ./bootstrap.sh
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install libsodium-dev -y
script:
  - ./venv/bin/py.test tests -v --color=yes
  - (set -e; [[ $(git diff) ]] && { git diff; exit 1; } || exit 0)
