language: python
sudo: required
python:
  - "2.7"
services:
  - couchdb
env:
  global:
    - TZ=Europe/Kiev
cache: pip
addons:
  hosts:
   - couchdb
before_install:
  - ./bootstrap.sh
before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
script:
  - ./bin/py.test tests -v --color=yes
  - (set -e; [[ $(git diff) ]] && exit 1 || exit 0)
